/** ABOUTME: Auto-generated backend projects index */
// Generated by: node src/scripts/build-projects.ts   , run `pnpm build:projects`
// Generated at: 2025-09-30T10:05:16.674Z
// DO NOT EDIT !!! - This file is automatically generated

import * as testBackendProject from '../../projects/test-backend-project/index';

/** 所有后端项目聚合 */
export const projects = {
  'test-backend-project': testBackendProject,
};

