/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiEnglishConfigPanel: typeof import('./src/components/AiEnglishConfigPanel.vue')['default']
    AutoColumn: typeof import('./src/components/AutoTable/AutoColumn.vue')['default']
    AutoColumnEdit: typeof import('./src/components/AutoTable/AutoColumnEdit.vue')['default']
    AutoFilter: typeof import('./src/components/AutoTable/AutoFilter.vue')['default']
    AutoForm: typeof import('./src/components/AutoTable/AutoForm.vue')['default']
    AutoTable: typeof import('./src/components/AutoTable/AutoTable.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CommonSettingBtns: typeof import('./src/components/system/CommonSettingBtns.vue')['default']
    GithubStar: typeof import('./src/components/system/GithubStar.vue')['default']
    GoogleAd: typeof import('./src/components/GoogleAd.vue')['default']
    HeartStackSpace_ts: typeof import('./src/components/icons/HeartStackSpace_ts.vue')['default']
    I18nSwitch: typeof import('./src/components/system/I18nSwitch.vue')['default']
    Message: typeof import('primevue/message')['default']
    RelationSelect: typeof import('./src/components/AutoTable/RelationSelect.vue')['default']
    RemoteSelect: typeof import('./src/components/base/RemoteSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartPopover: typeof import('./src/components/base/SmartPopover.vue')['default']
    SponsorshipCard: typeof import('./src/components/SponsorshipCard.vue')['default']
    TestWarningBanner: typeof import('./src/components/system/TestWarningBanner.vue')['default']
    ThemeToggle: typeof import('./src/components/system/ThemeToggle.vue')['default']
    UserSettingBtn: typeof import('./src/components/system/UserSettingBtn.vue')['default']
  }
}
