/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiEnglishConfigPanel: typeof import('./src/components/AiEnglishConfigPanel.vue')['default']
    AiEnglishTips: typeof import('./src/components/AiEnglishTips.vue')['default']
    AutoColumn: typeof import('./src/components/AutoTable/AutoColumn.vue')['default']
    AutoColumnEdit: typeof import('./src/components/AutoTable/AutoColumnEdit.vue')['default']
    AutoFilter: typeof import('./src/components/AutoTable/AutoFilter.vue')['default']
    AutoForm: typeof import('./src/components/AutoTable/AutoForm.vue')['default']
    AutoTable: typeof import('./src/components/AutoTable/AutoTable.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Column: typeof import('primevue/column')['default']
    CommonSettingBtns: typeof import('./src/components/system/CommonSettingBtns.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    GithubStar: typeof import('./src/components/system/GithubStar.vue')['default']
    GlassBlur: typeof import('./src/components/GlassBlur.vue')['default']
    GoogleAd: typeof import('./src/components/GoogleAd.vue')['default']
    HeartStackSpace_ts: typeof import('./src/components/icons/HeartStackSpace_ts.vue')['default']
    I18nSwitch: typeof import('./src/components/system/I18nSwitch.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LineRenderer: typeof import('./src/components/LineRenderer.vue')['default']
    Message: typeof import('primevue/message')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ParagraphRenderer: typeof import('./src/components/ParagraphRenderer.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RelationSelect: typeof import('./src/components/AutoTable/RelationSelect.vue')['default']
    RemoteSelect: typeof import('./src/components/base/RemoteSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('primevue/slider')['default']
    SmartPopover: typeof import('./src/components/base/SmartPopover.vue')['default']
    SponsorshipCard: typeof import('./src/components/SponsorshipCard.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TestWarningBanner: typeof import('./src/components/system/TestWarningBanner.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeToggle: typeof import('./src/components/system/ThemeToggle.vue')['default']
    Tooltip: typeof import('./src/components/base/Tooltip.vue')['default']
    UserSettingBtn: typeof import('./src/components/system/UserSettingBtn.vue')['default']
    WordRenderer: typeof import('./src/components/WordRenderer.vue')['default']
  }
}

// For TSX support
declare global {
  const AiEnglishConfigPanel: typeof import('./src/components/AiEnglishConfigPanel.vue')['default']
  const AiEnglishTips: typeof import('./src/components/AiEnglishTips.vue')['default']
  const AutoColumn: typeof import('./src/components/AutoTable/AutoColumn.vue')['default']
  const AutoColumnEdit: typeof import('./src/components/AutoTable/AutoColumnEdit.vue')['default']
  const AutoFilter: typeof import('./src/components/AutoTable/AutoFilter.vue')['default']
  const AutoForm: typeof import('./src/components/AutoTable/AutoForm.vue')['default']
  const AutoTable: typeof import('./src/components/AutoTable/AutoTable.vue')['default']
  const Avatar: typeof import('primevue/avatar')['default']
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const Carousel: typeof import('primevue/carousel')['default']
  const Column: typeof import('primevue/column')['default']
  const CommonSettingBtns: typeof import('./src/components/system/CommonSettingBtns.vue')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const GithubStar: typeof import('./src/components/system/GithubStar.vue')['default']
  const GlassBlur: typeof import('./src/components/GlassBlur.vue')['default']
  const GoogleAd: typeof import('./src/components/GoogleAd.vue')['default']
  const HeartStackSpace_ts: typeof import('./src/components/icons/HeartStackSpace_ts.vue')['default']
  const I18nSwitch: typeof import('./src/components/system/I18nSwitch.vue')['default']
  const InputSwitch: typeof import('primevue/inputswitch')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const LineRenderer: typeof import('./src/components/LineRenderer.vue')['default']
  const Message: typeof import('primevue/message')['default']
  const Paginator: typeof import('primevue/paginator')['default']
  const ParagraphRenderer: typeof import('./src/components/ParagraphRenderer.vue')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RelationSelect: typeof import('./src/components/AutoTable/RelationSelect.vue')['default']
  const RemoteSelect: typeof import('./src/components/base/RemoteSelect.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Slider: typeof import('primevue/slider')['default']
  const SmartPopover: typeof import('./src/components/base/SmartPopover.vue')['default']
  const SponsorshipCard: typeof import('./src/components/SponsorshipCard.vue')['default']
  const Tag: typeof import('primevue/tag')['default']
  const TestWarningBanner: typeof import('./src/components/system/TestWarningBanner.vue')['default']
  const Textarea: typeof import('primevue/textarea')['default']
  const ThemeToggle: typeof import('./src/components/system/ThemeToggle.vue')['default']
  const Tooltip: typeof import('./src/components/base/Tooltip.vue')['default']
  const UserSettingBtn: typeof import('./src/components/system/UserSettingBtn.vue')['default']
  const WordRenderer: typeof import('./src/components/WordRenderer.vue')['default']
}