/** ABOUTME: Auto-generated frontend routes index */
// Generated by vite-plugin-auto-routes
// Generated at: 2025-10-01T03:45:21.978Z
// DO NOT EDIT !!! - This file is automatically generated

// 动态导入项目路由
import * as dynamictestmodule from '../../projects/dynamic-test-module/main.routeMap.ts';
import * as testproject from '../../projects/test-project/main.routeMap.ts';

/** 所有前端项目路由聚合 */
export const routeModels = {
  ...dynamictestmodule.default,
  ...testproject.default,
};

/** 路由统计信息 */
export const routeStats = {
  projectRoutes: 2,
  generatedAt: '2025-10-01T03:45:21.978Z'
};

